
#version: '3.8'

services:
  api:
    container_name: sae_backend
    build:
      context: ./backend
    ports:
      - "3000:3000"
#    environment:
#      - SUPABASE_URL
#      - SUPABASE_SERVICE_ROLE_KEY
#      - SUPABASE_JWT_SECRET
    env_file:
      - ./backend/.env
    healthcheck:
      # Use curl to hit the /health endpoint. Add the -f flag to ensure it fails on HTTP errors.
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    container_name: sae_frontend
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    command: npm run dev -- --host
