@host = {{host}}
@appName = {{appName}}
@email = {{email}}
@password = {{password}}

###
# @name loginSuccess
# Positive Test: Log in with a valid user
# Note: This assumes the user from register.http was successfully created.
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "AppToRegisterWith": "{{appName}}"
}

###
# @name loginInvalidPassword
# Negative Test: Attempt to log in with an incorrect password
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "wrong-password",
  "AppToRegisterWith": "{{appName}}"
}

###
# @name loginNonExistentUser
# Negative Test: Attempt to log in with a user that does not exist
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "non-existent-user@example.com",
  "password": "{{password}}",
  "AppToRegisterWith": "{{appName}}"
}

###
# @name loginInvalidApp
# Negative Test: Attempt to log in with an application that does not exist
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "AppToRegisterWith": "NonExistentApp"
}