@host = {{host}}
@appName = {{appName}}
@email = {{email}}
@clientId = {{clientId}}
@clientSecret = {{clientSecret}}

###
# @name getClientTokenForMagic
# Step 1: Acquire the Client JWT.
POST {{host}}/auth/client-token
Content-Type: application/json

{
  "clientId": "{{clientId}}",
  "clientSecret": "{{clientSecret}}"
}

###
# @name magicLinkSuccess
# Positive Test: Request a magic link for a valid user
@client_jwt = {{getClientTokenForMagic.response.body.client_jwt}}
POST {{host}}/auth/magic
Content-Type: application/json
Authorization: Bearer {{client_jwt}}

{
  "email": "{{email}}",
  "AppToRegisterWith": "{{appName}}"
}

###
# @name magicLinkWithoutClientToken
# Negative Test: Request a magic link without a client token
POST {{host}}/auth/magic
Content-Type: application/json

{
  "email": "{{email}}",
  "AppToRegisterWith": "{{appName}}"
}